name: workflow-dispatch

on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: |
          npm install -g yarn
          yarn install
          yarn test
          yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: geeknight
          path: ./build